[build]
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000 # Vite 개발 서버 포트와 충돌 방지

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200