[build]
  command = "npm install --prefix frontend && npm run build"
  functions = "netlify/functions"
  publish = "frontend/dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 3000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200